Q1 Write a Python script that reads a text file and creates a new file containing the word frequencies of all words in descending order.

In [ ]:
char_frequency = {}

with open('1.txt', 'r') as file:
    content = file.read()
    for char in content:
        if char in char_frequency:
            char_frequency[char] += 1
        else:
            char_frequency[char] = 1

with open('char_frequency.txt', 'w') as freq_file:
    for char, freq in char_frequency.items():
        freq_file.write(f"{char}: {freq}\n")



Q2 Write a program that takes a word as input, searches for it in a given file, replaces all its occurrences with another word, and writes the changes back to the same file.


In [ ]:
old = input("Enter old word to be replaced : ")
new = input("Enter new word to be replaced with : ")
with open('1.txt', 'r+') as file:
    content = file.read()
    file.seek(0)
    file.write(content.replace(old, new))
    file.truncate()

Q3 You have multiple text files in a folder. Write a Python program that merges all these files into a single file while maintaining the order of their creation time.

In [6]:
import os

def merge_files(folder_path, output_file):
    with open(output_file, 'w') as outfile:
        for filename in sorted(os.listdir(folder_path), key=os.path.getctime):
            if filename.endswith('.txt'):
                with open(os.path.join(folder_path, filename), 'r') as infile:
                    outfile.write(infile.read() + '\n')

merge_files('./', 'merged_output.txt')

Q4 Given a CSV file containing missing or inconsistent data, write a Python script to clean the data by:
- Removing duplicate rows
- Filling missing values with the column average
- Removing special characters from column names


In [60]:
import pandas as pd

data = pd.read_csv("data.csv", index_col="Name")
data = data[~data.duplicated()]
data.fillna(data[["Salary", "Age"]].mean(), inplace=True)
data.index = data.index.str.replace('[^A-Za-z0-9_]', '', regex=True)
data
# data[["Salary", "Age"]].mean()

Age        Salary   Department
Name                                         
JohnDoe       28.0  50000.000000  Engineering
JaneSmith     34.0  60000.000000    Marketing
AliceJohnson  33.0  55000.000000        Sales
BobBrown      45.0  55428.571429  Engineering
CharlieDavis  30.0  70000.000000    Marketing
EveWhite      29.0  48000.000000        Sales
InvalidName   25.0  40000.000000           HR
DavidWilson   40.0  65000.000000  Engineering

Q5 Write a Python script to encrypt a text file using a simple substitution cipher and then write another script to decrypt it back to its original form

In [61]:
def encrypt_file(input_file, output_file, shift):
    with open(input_file, 'r') as infile:
        text = infile.read()
    
    encrypted_text = ''.join(
        chr((ord(char) - 65 + shift) % 26 + 65) if char.isupper() else
        chr((ord(char) - 97 + shift) % 26 + 97) if char.islower() else char
        for char in text
    )
    
    with open(output_file, 'w') as outfile:
        outfile.write(encrypted_text)

def decrypt_file(input_file, output_file, shift):
    decrypt_shift = -shift
    encrypt_file(input_file, output_file, decrypt_shift)

# Example usage
encrypt_file('input.txt', 'encrypted.txt', 3)
decrypt_file('encrypted.txt', 'decrypted.txt', 3)




Q6 Write a NumPy operation to extract only the even numbers without using loops from a given array
You have a large NumPy array: arr = np.random.randint(1, 100, (1000, 1000)) Find the sum of all prime numbers in “arr” efficiently. Avoid using Python loops.

In [125]:
import numpy as np
arr = np.random.randint(1, 100, (1000, 1000))
arr[arr%2==0]

array([34, 74, 34, ..., 70, 24, 12], dtype=int32)

Q7 Make a square matrix: Write a NumPy one-liner to rotate it 90 degrees clockwise.

In [128]:
import numpy as np
arr = np.array([
    [1,2,3],
    [4,5,6],
    [0,8,9]
])
rotated_arr = np.rot90(arr, k=-1)
rotated_arr

array([[0, 4, 1],
       [8, 5, 2],
       [9, 6, 3]])

Q8 Generate a 1,000,000-element NumPy array of random numbers between -100 and 100. Compute:The mean,The median,The standard deviation, The 90th percentile Using efficient NumPy functions.


In [166]:
random_array = np.random.uniform(-100, 100, 1000000)
mean_value = np.mean(random_array)
median_value = np.median(random_array)
std_deviation = np.std(random_array)
percentile_90 = np.percentile(random_array, 90)

mean_value, median_value, std_deviation, percentile_90



(np.float64(-0.0945233551878862),
 np.float64(-0.1493678876103175),
 np.float64(57.715122984810705),
 np.float64(79.94254710360313))

Q9 Generate a random symmetric matrix of size (4,4). Compute:
The determinant,The eigenvalues and eigenvectors,The inverse using NumPy functions

In [168]:
symmetric_matrix = np.random.rand(4, 4)
symmetric_matrix = (symmetric_matrix + symmetric_matrix.T) / 2

determinant = np.linalg.det(symmetric_matrix)
eigenvalues, eigenvectors = np.linalg.eig(symmetric_matrix)
inverse_matrix = np.linalg.inv(symmetric_matrix)

symmetric_matrix, determinant, eigenvalues, eigenvectors, inverse_matrix



(array([[0.65670816, 0.13418635, 0.49495156, 0.23955196],
        [0.13418635, 0.80518147, 0.20259466, 0.7270904 ],
        [0.49495156, 0.20259466, 0.95412011, 0.48624553],
        [0.23955196, 0.7270904 , 0.48624553, 0.25480729]]),
 np.float64(-0.14703678817097227),
 array([ 1.84178596,  0.85321366,  0.29403705, -0.31821964]),
 array([[ 0.40328784,  0.44585592,  0.79888815, -0.0186853 ],
        [ 0.50240905, -0.69683354,  0.12366037, -0.49670542],
        [ 0.59960837,  0.49475863, -0.58426297, -0.23306754],
        [ 0.4747777 , -0.26617553, -0.07157244,  0.83583139]]),
 array([[ 2.4907463 ,  0.05268762, -1.21127186, -0.18051405],
        [ 0.05268762, -0.01713088, -0.8500245 ,  1.62144066],
        [-1.21127186, -0.8500245 ,  1.47235819,  0.75460799],
        [-0.18051405,  1.62144066,  0.75460799, -1.97253464]]))

Q10 WAP to find the second-largest value in each column of a DataFrame without using .sort_values()?

In [ ]:
import pandas as pd

data = pd.read_csv("data.csv", index_col="Name")
data = data[~data.duplicated()]
data.fillna(data[["Salary", "Age"]].mean(), inplace=True)
data.index = data.index.str.replace('[^A-Za-z0-9_]', '', regex=True)
data["age_max"] = data["age"] > data["Age"].max()

KeyError: 'age'